### ISSUE TITLE
manipulation of PS1 is not needed

### ISSUE THREAD

**Issue by michaelkrupp** [erikw/tmux-powerline#188]
Tmux provides `#{pane_current_path}` which can be read in external scripts:

`PANE_PWD="$( tmux display -p '#{pane_current_path}' )"`

**Comment by IngoHeimbach** [comment]
This issue is very old but since all recent versions of tmux have `pane_current_path` it would be nice to add this feature to avoid PS1 manipulation.

`pane_current_path` was first introduced in tmux 1.7 but was removed later (I think in 2.0). However, it was added again in version 2.1. These are the relevant commits in the tmux repository:

- [b831f863](https://github.com/tmux/tmux/commit/b831f8635409883e2ad2b6feedf05821f8f2ea84)
- [2c6ea705](https://github.com/tmux/tmux/commit/2c6ea705fd05966c00534623a9b8fa3431df98f5)

Maybe it would be senseful to add a version check and to use the tmux working directory query function if it is available. One advantage is, that tmux powerline would recognize changes to the current working directory even when running applications like vim.
