### ISSUE TITLE
powerline fonts doesn't work

### ISSUE THREAD

**Issue by christian-bromann** [erikw/tmux-powerline#190]
Hi,

I am running Mac OS X Yosemite and tried a lot of stuff to get the fonts imported but for some reasons I get this:

![screen shot 2014-10-31 at 15 49 36](https://cloud.githubusercontent.com/assets/731337/4862500/2c580f86-610d-11e4-9048-71811918c7b5.png)

Any idea why this happens?

**Comment by yukie-** [comment]
hey everyone, I hope you ended up figuring this out. This is due to not having patched fonts. make sure you're using this repo https://github.com/powerline/fonts

![fontsss](https://cloud.githubusercontent.com/assets/10278096/8994521/e0c837fa-36d9-11e5-8e0c-eb06fa5ca940.png)

I'm still configuring my .tmux.conf but you can see here the fonts are at least patched correctly. 

I'm on Yosemite 10.10.13 

Hope this helps!

**Comment by erikw** [comment]
I'm closing this stale issue due to age.
