### ISSUE TITLE
Issue with weather.sh not displaying fahrenheit

### ISSUE THREAD

**Issue by mr-hespicable** [erikw/tmux-powerline#329]
setting `TMUX_POWERLINE_SEG_WEATHER_UNIT` to `f` doesn't show fahrenheit...
it doesn't show any numbers at all, just changes  `°C` to `°F`.

my weather.sh config is as follows:
```
weather.sh {
	# The data provider to use. Currently only "yahoo" is supported.
	export TMUX_POWERLINE_SEG_WEATHER_DATA_PROVIDER="yrno"
	# What unit to use. Can be any of {c,f,k}.
	export TMUX_POWERLINE_SEG_WEATHER_UNIT="f"
	# How often to update the weather in seconds.
	export TMUX_POWERLINE_SEG_WEATHER_UPDATE_PERIOD="600"
	# Name of GNU grep binary if in PATH, or path to it.
	export TMUX_POWERLINE_SEG_WEATHER_GREP="grep"
	# Location of the JSON parser, jq
	export TMUX_POWERLINE_SEG_WEATHER_JSON="jq"
	# Your location
	# Latitude and Longitude for use with yr.no
	TMUX_POWERLINE_SEG_WEATHER_LAT="42.361145"
	TMUX_POWERLINE_SEG_WEATHER_LON="-71.057083"
}
```
latitude and longitude are obviously edited. i'm not going to dox myself, guys.

this is what's displayed on the statusline
![image](https://github.com/erikw/tmux-powerline/assets/85052021/cc4d3625-5191-4a7c-b00d-e71b7069fd1e)

**Comment by erikw** [comment]
Hey, sry slow reply.

The weather segment works for me with the provider `yrno` and with both C and F units. Does Celsius work for you or it's also blank? 

Notice that if you change some weather configuration, it will take a while until it takes effect because the result is cached, to not call the weather provider too often. You can shorten the cache but changing here:

https://github.com/erikw/tmux-powerline/blob/033e3ae68805f81f026847647b829c9b00322f2f/segments/weather.sh#L1-L4


If also Celsius is not showing and data, please continue using these debugging instructions to find out what's going on. It could be anything from missing required tools or configuration that is slightly off ¯\_(ツ)_/¯ 

https://github.com/erikw/tmux-powerline#debugging

**Comment by mr-hespicable** [comment]
Celsius works for me

**Comment by mr-hespicable** [comment]
++ export TMUX_POWERLINE_SEG_WEATHER_DATA_PROVIDER=yrno
++ TMUX_POWERLINE_SEG_WEATHER_DATA_PROVIDER=yrno
++ export TMUX_POWERLINE_SEG_WEATHER_UNIT=c
++ TMUX_POWERLINE_SEG_WEATHER_UNIT=c
++ export TMUX_POWERLINE_SEG_WEATHER_UPDATE_PERIOD=10
++ TMUX_POWERLINE_SEG_WEATHER_UPDATE_PERIOD=10
++ export TMUX_POWERLINE_SEG_WEATHER_GREP=grep
++ TMUX_POWERLINE_SEG_WEATHER_GREP=grep
++ export TMUX_POWERLINE_SEG_WEATHER_JSON=jq
++ TMUX_POWERLINE_SEG_WEATHER_JSON=jq
++ TMUX_POWERLINE_SEG_WEATHER_LAT=51.460190
++ TMUX_POWERLINE_SEG_WEATHER_LON=-0.294750
++ set +x
cat: /sys/class/power_supply/BAT1/status: No such file or directory
/home/leon/.config/tmux/plugins/tmux-powerline/segments/battery.sh: line 100: [: too many arguments
/h/home/leon/.config/tmux/plugins/tmux-powerline/segments/weather.sh: line 88: bc: command not found
/home/leon/.config/tmux/plugins/tmux-powerline/segments/weather.sh: line 89: [: : integer expression expected

and this is what it says when i use the stuff in #debugging

**Comment by mr-hespicable** [comment]
the issue was i hadn't installed bc.
i hate my life 😭 im sorry for making this im literally so dumb
thanks anyway you helped me a lot <3
