### ISSUE TITLE
Patched Font Glyphs do not appear on the Tmux Powerline.

### ISSUE THREAD

**Issue by vbajpai** [erikw/tmux-powerline#33]
Issue: I do not see the Glyphs in the tmux powerline :-

![Imgur](http://i.imgur.com/oBZZz.png)

OS: Mac OS X 10.7.4
Terminal Application: iTerm 2

```
>> tmux -V
tmux 1.6

>> bash --version
GNU bash, version 4.2.37(2)-release (i386-apple-darwin11.2.0)

>> zsh --version
zsh 5.0.0 (x86_64-apple-darwin11.2.0)

>> ./status-left.sh 
#[bg=colour148] #[fg=colour148, bg=colour148]#[fg=colour234,bg=colour148]0:1.1 #[fg=colour148, bg=colour33]⮀#    
[fg=colour0,bg=colour33]   ilab #[fg=colour33, bg=colour24]⮀#[fg=colour255,bg=colour24]   ⓛ 10.50.203.149   #[fg=white,   
bg=colour24]⮁#[fg=colour255,bg=colour24]   ⓦ 212.201.44.246   #[fg=colour24, bg=colour235]⮀#[fg=red,bg=colour235]   #
[default]

>> ./status-right.sh
#[fg=colour237, bg=colour235]⮂#[fg=colour167,bg=colour237]    0.65 0.84 0.86 #[fg=colour37, bg=colour237]⮂#  
[fg=colour255,bg=colour37]   ✈ 26°C    #[fg=colour235, bg=colour37]⮂#[fg=colour136,bg=colour235]   Sat #[fg=default,   
bg=colour235]⮃#[fg=colour136,bg=colour235]   2012-07-28 #[fg=default, bg=colour235]⮃#[fg=colour136,bg=colour235]   14:07  
#[default]
```

My tmux configuration:

```
# split panes
bind | split-window -h
bind - split-window -v

# resize panes
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# enable 256-colors
set -g default-terminal "screen-256color"

# enable utf-8 on status bar
set -g status on
set -g status-utf8 on

# status refresh interval
set -g status-interval 2

# status left
set -g status-left-length 60
set -g status-left "#(~/.tmux/tmux-powerline/status-left.sh)"

# status right
set -g status-right-length 90
set -g status-right "#(~/.tmux/tmux-powerline/status-right.sh)"

# solarized theme
source ~/.tmux/tmux-colors-solarized/tmuxcolors.conf

# window and pane start index
set -g base-index 1
set -g pane-base-index 1

# center the window list
set -g status-justify centre

# vi mode for the buffer
setw -g mode-keys vi

# command sequence for nested tmux session
bind-key a send-prefix

# remap prefix to ctrl-a
set -g prefix C-a
```

I am using a patched Ubuntu Mono font. I previously tried using the patched font available for download from the vim-powerline wiki page, but then I also tried patching it myself, but to no avail. 

I personally do not see that the patched font is the issue, since running the scripts independently do produce the glyphs, they just don't appear on the tmux status line for some reason.

**Comment by MoOmEeN** [comment]
Looks like separator characters specified in themes/default.sh file don't work with patched fonts anymore.
I copied the characters from vim-airline doc (airline.txt: g:airline_left_sep, g:airline_left_alt_sep, g:airline_right_sep, g:airline_right_alt_sep) file, and now it works for me.

**Comment by dtothefp** [comment]
I know this is an old issue but I saw @erikw your comment on viewing the glyph symbol. On my work Macbook I use vim airline and tmux powerline works just by having patched fonts intalled and this in my .tmux.conf

```
# Powerline symbols: ⮂ ⮃ ⮀ ⮁ ⭤
set -g status-left-length 32
set -g status-right-length 150
set -g status-interval 5

set -g status-left '#[fg=colour16,bg=colour254,bold] #S #[fg=colour254,colour=238,nobold]'

set -g status-right '#[fg=colour245]⮃ %R ⮃ %d %b #[fg=colour254,bg=colour234,nobold]⮂#[fg=colour16,bg=colour254,bold] #h '

set -g window-status-format "#[fg=white,bg=colour234] #I #W "
set -g window-status-current-format "#[fg=colour234,bg=colour39]⮀ #[fg=colour16,bg=colour39,noreverse,bold] #I ⮁ #W #[fg=colour39,bg=colour234,nobold]⮀"
```

This works great but when I use the exact same config in my home Macbook the glyphs display as small boxes with circles in the center. As you can see from the screenshot that patched fonts in iTerm vim airline work fine:

![screen shot 2015-03-09 at 12 29 11 am](https://cloud.githubusercontent.com/assets/4656726/6549972/a97ff938-c5f3-11e4-9c0b-5fc9c6e8e5ed.png)

Is there something I'm not understanding about patched fonts and their application because even if I view your glyph above in the GitHub page on my old machine I see a blank box whereas on my new one I see an arrow?

**Comment by erikw** [comment]
As seen in the most recent commits, I took in a pull request that switches
to use glyphs from the new generation of powelibe parched fonts. Links in
README are updated. Probably one of your machines has the older type of
font and the other a the newer generation.

-- 
Erik Westrup
<erik.westrup@gmail.com>
(+46) 0738-286060 | 2r.se
Lagerbrings väg 8E, 22460 Lund, Sweden
-----------------------------------------
This email is encrypted with 2ROT-13.

**Comment by dtothefp** [comment]
@erikw yeh I guess that is where my confusion arises from on how to update my machine with the older type to the newer? I thought importing the font into Font Book and applying it in iTerm preferences > profiles > text would do the trick. Any info on how to update these font glyphs system wide would be helpful if that is the issue.

Like I said I'm not using `tmux-powerline` but when I do the font glyphs actually work briefly. The problem is when I start a new tmux session/window the `tmux-powerline` will flash on, usually doubled up like the screenshot, and then disappear on it's own or when I enter text into the terminal. In addition, there is a white bar beneath the lines with the glyphs that looks like it contains the normal tmux status display.  My settings are as you suggested:
- disabled airline tmuxline
- create snapshot of airline theme
- `soure-file` the snapshot in my `tmux.conf`

![screen shot 2015-03-09 at 9 53 03 am](https://cloud.githubusercontent.com/assets/4656726/6559292/50378052-c658-11e4-9a53-ea8b40750122.png)
